<?php

/*
 *@file
 * Implementing some hook functions.
 */

use Drupal\node\Entity\Node;

function batch_form_cron(){

    $slogan =\Drupal::service('config.factory')->getEditable('system.site')->get('slogan');
        if (is_numeric($slogan)) {
          $slogan = $slogan + 1;
          \Drupal::service('config.factory')->getEditable('system.site')->set('slogan',$slogan)->save();
        }
        else{
         \Drupal::service('config.factory')->getEditable('system.site')->set('slogan',0)->save();
        }

    $query = \Drupal::entityQuery('node')->condition('nid','263');    // The ID of the node.
    $nids = $query->execute();
    $nodes = Node::loadMultiple($nids);
        foreach ($nodes as $node) {
          $node->set("title", strtoupper($node->title->value));
          $node->save();
        }
    \Drupal::messenger()->addMessage('Nodes updated');
}
